### ISSUE TITLE
MediaPlayerUI.NET

### ISSUE THREAD

**Issue by mysteryx93** [hudec117/Mpv.NET#2]
Thanks for the updates to Mpv.NET!

I think I've finally completed MediaPlayerUI.NET, did a lot of code restructuring. Perhaps you could put a link to it in your project description? You can also test it if you see anything missing. It's working pretty good now.
https://github.com/mysteryx93/MediaPlayerUI.NET

All that's left is to publish to NuGet.

**Comment by hudec117** [comment]
No problem, thanks for the suggestions!

Done.
