### ISSUE TITLE
MediaFinished event not firing

### ISSUE THREAD

**Issue by mysteryx93** [hudec117/Mpv.NET#3]
I see you added a MediaFinished event. However, in my case, the event isn't firing at all.

**Comment by hudec117** [comment]
Hiya, I'll look into this.

What properties did you have set? (e.g. KeepOpen, Loop etc?

**Comment by mysteryx93** [comment]
Neither are set. MediaUnloaded is fired but MediaFinishes isn't,

**Comment by hudec117** [comment]
The problem seemed to be that when KeepOpen was set to No and the media unloaded, only the MediaUnloaded event would be invoked. I've changed it to also invoke MediaFinished in this case.

**Comment by mysteryx93** [comment]
OK but you haven't committed your changes yet? eofReachedUserData is called but eventProperty.DataString is null instead of containing "yes"

**Comment by hudec117** [comment]
> eofReachedUserData is called but eventProperty.DataString is null instead of containing "yes"
I cannot seem to replicate this, could you provide more detail?

I can release what I've pushed to dev as 0.7.1 if you like.

**Comment by hudec117** [comment]
@mysteryx93 are you still having this issue? If so, please provide more detail.

**Comment by hudec117** [comment]
Failed to re-produce and no reply.
